# Lecture 5 – Evaluation, Names, Data Types

### Data 6, Fall 2024

In [37]:
#from datascience import *
from numpy import * #Why is this not preferred?
import numpy as np #Why is this preferred?
import datascience as ds

In [63]:
c_temps = ds.make_array(30, 18, -4.5, 0, 3)

type(c_temps.item(0))


float

## Warmup

In [24]:
pop_2020 = make_array(5.025, .732, 7.178, 3.012, 39.500)
pop_2021 = make_array(5.040, .733, 7.276, 3.026, 39.238)

In [25]:
pop_2021 - pop_2020

array([ 0.015,  0.001,  0.098,  0.014, -0.262])

In [8]:
average(pop_2020)

11.089400000000001

In [3]:
x = print(print(3))
print(x)

3
None
None


<br/><br/>

# Array Functions
Array functions in Python, such as len, min, and max, are essential tools for manipulating and analyzing arrays or lists of data. 

The `len` function returns the length of an array, providing the number of elements it contains. This is useful for determining the size of an array dynamically. 

The `min` function identifies the smallest value within an array, while the `max` function retrieves the largest value. 

The `sum` function sums all of the values in an array.

These functions are handy when searching for extremities or performing basic statistical analysis on arrays. 

With their simplicity and efficiency, `len`, `min`, `max`, and `sum` are versatile array functions that greatly enhance Python's capabilities in data processing and analysis.

In [8]:
empty_arr = make_array()
int_arr = make_array(3, -4, 0, 5, 2)
str_arr = make_array("cm", "m", "in", "ft", "yd")

In [9]:
print(empty_arr)
print(int_arr)
print(str_arr)

[]
[ 3 -4  0  5  2]
['cm' 'm' 'in' 'ft' 'yd']


`len()`

In [10]:
len(str_arr)

5

In [11]:
len(empty_arr)

0

`min()`, `max()`

In [12]:
min(int_arr)

-4

In [13]:
max(str_arr)

'yd'

`sum()`

In [14]:
sum(int_arr)

6

In [15]:
sum(str_arr)

TypeError: unsupported operand type(s) for +: 'int' and 'numpy.str_'

How would you compute the average of an array arr?

In [ ]:
arr = make_array(30, -40, -4.5, 0, 35)
avg = ...
avg

## NumPy Functions

In [16]:
import numpy as np

Elementwise functions

In [17]:
numbers_arr = make_array(5, 4, 9, 12, 100)
numbers_arr

array([  5,   4,   9,  12, 100])

In [18]:
np.sqrt(numbers_arr)

array([  2.23606798,   2.        ,   3.        ,   3.46410162,  10.        ])

In [19]:
np.log(numbers_arr)   # natural log

array([ 1.60943791,  1.38629436,  2.19722458,  2.48490665,  4.60517019])

In [20]:
np.log10(numbers_arr) # log base 10

array([ 0.69897   ,  0.60205999,  0.95424251,  1.07918125,  2.        ])

In [21]:
np.sin(numbers_arr)

array([-0.95892427, -0.7568025 ,  0.41211849, -0.53657292, -0.50636564])

In [22]:
np.sqrt(144)

12.0

Common functions

In [27]:
pop_2020

array([  5.025,   0.732,   7.178,   3.012,  39.5  ])

In [26]:
np.mean(pop_2020)

11.089400000000001

In [28]:
np.average(pop_2020)

11.089400000000001

In [29]:
np.sum(pop_2020)

55.447000000000003

In [30]:
np.prod(pop_2020)

3141.2511768275995

In [31]:
np.count_nonzero(make_array(1, 2, 3, 0, 4, 0, -5))

5

### Even More Functions

In [32]:
daily_high_temps = make_array(73, 71, 69, 72, 76, 74, 75)
daily_high_temps

array([73, 71, 69, 72, 76, 74, 75])

In [33]:
np.diff(daily_high_temps)

array([-2, -2,  3,  4, -2,  1])

In [34]:
pop_by_year = make_array(23, 45, 93, 101, 118)
pop_by_year

array([ 23,  45,  93, 101, 118])

In [39]:
np.cumsum(pop_by_year)

array([ 23,  68, 161, 262, 380])

In [40]:
np.arange(10)
make_array(0, 1, 2, 3, 4...9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr = np.arange(3, 9)
arr

array([3, 4, 5, 6, 7, 8])

In [43]:
np.arange(3, 14, 7)

array([ 3, 10])

In [44]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
np.sum(arr)

55

In [46]:
np.arange(3, 11, 2)

array([3, 5, 7, 9])

In [47]:
np.arange(10, 1, -3)

array([10,  7,  4])

# Indexing

In [48]:
sq_array = make_array(1, 4, 9, 16, 25)
sq_array

array([ 1,  4,  9, 16, 25])

In [49]:
type(sq_array)

numpy.ndarray

In [50]:
int_arr = make_array(3, -4, 0, 5, 2)
int_arr

array([ 3, -4,  0,  5,  2])

In [51]:
int_arr.item(0)

3

In [52]:
int_arr.item(3)

5

In [53]:
int_arr.item(5)

IndexError: index 5 is out of bounds for axis 0 with size 5

In [54]:
int_arr.item(len(int_arr) - 1) #Grab the last item inside int_arr

2

In [55]:
int_arr.item(-1)

2

In [56]:
int_arr.item(-3)

0

In [57]:
test_array = make_array(10, 14, 67, -1.5, 3.2, 2.72, 104, 81, 3.14159)

In [58]:
# first (0th element)
test_array.item(0)

10.0

In [59]:
# second (1st element)
test_array.item(1)

14.0

In [60]:
# last element
test_array.item(len(test_array) - 1)
# OR 
test_array.item(-1)

3.14159

In [61]:
# second to last element
test_array.item(-2)

81.0

What is the value of `five` after running this code?

In [ ]:
threes = make_array(3, 6, 9, 12, 15)
five = threes.item(-1) + threes.item(1)
five